select o.COD_ORCAMENTO,SercOrc.ORCAMENTO_COD_ORCAMENTO,SercOrc.SERVICO_COD_SERICO,COD_SERVICO,Val_Servico from servico
Join SERVICO_Has_ORCAMENTO as SercOrc on COD_SERVICO = SercOrc.SERVICO_COD_SERICO
Join ORCAMENTO as o on o.COD_ORCAMENTO = SercOrc.ORCAMENTO_COD_ORCAMENTO
where Val_Servico > 3000;


select o.COD_ORCAMENTO from servico
Join SERVICO_Has_ORCAMENTO as SercOrc on COD_SERVICO = SercOrc.SERVICO_COD_SERICO
Join ORCAMENTO as o on o.COD_ORCAMENTO = SercOrc.ORCAMENTO_COD_ORCAMENTO
where Val_Servico > 3000;



